# Generated by Django 4.1.5 on 2023-01-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(db_index=True, max_length=999)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=999)),
                ('ip_address', models.CharField(max_length=999)),
                ('login', models.CharField(max_length=999)),
                ('password', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='CarParkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(db_index=True, max_length=999)),
                ('valid_until', models.DateTimeField(db_index=True)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Laurent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=999)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='LEDBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=999)),
                ('ip_address', models.CharField(max_length=999)),
            ],
        ),
    ]
